spring:
  config:
    import: application-secret.yml
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true


logging:
  level:
    log4jdbc.log4j2: WARN
server:
  servlet:
    context-path: /api/v1
